name: build
on:
  workflow_dispatch:
  pull_request:
  push:
    #    branches:
    #  - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: "temurin"
          cache: 'gradle'

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: app/build/outputs/apk/debug/*.apk
